#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

# name: Delete old workflow runs
# on:
#   repository_dispatch:
#   workflow_dispatch:
#     inputs:
#       ssh:
#         description: 'SSH connection to Actions'
#         required: false
#         default: 'false'
#   schedule:
#     - cron: 43 5 * * *

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: 删除旧的工作流和固件
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.ACTIONS_RELEASE }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: Delete old workflow runs
          retain_days: 0
          keep_minimum_runs: 1
